package bernardo.venda.pojo;
// Generated Feb 3, 2016 4:08:05 PM by Hibernate Tools 4.3.1


import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Categoria generated by hbm2java
 */
@Entity
@Table(name = "categoria"
        , catalog = "vendabd"
)
public class Categoria implements java.io.Serializable {


    private Integer idCategoria;
    private String descricao;
    private Set<Produto> produtos = new HashSet<Produto>(0);

    public Categoria() {
    }


    public Categoria(String descricao) {
        this.descricao = descricao;
    }

    public Categoria(String descricao, Set<Produto> produtos) {
        this.descricao = descricao;
        this.produtos = produtos;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)


    @Column(name = "idCategoria", unique = true, nullable = false)
    public Integer getIdCategoria() {
        return this.idCategoria;
    }

    public void setIdCategoria(Integer idCategoria) {
        this.idCategoria = idCategoria;
    }


    @Column(name = "descricao", nullable = false, length = 45)
    public String getDescricao() {
        return this.descricao;
    }

    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "categoria")
    public Set<Produto> getProdutos() {
        return this.produtos;
    }

    public void setProdutos(Set<Produto> produtos) {
        this.produtos = produtos;
    }


}


