package bernardo.venda.pojo;
// Generated Feb 3, 2016 4:08:05 PM by Hibernate Tools 4.3.1


import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Cliente generated by hbm2java
 */
@Entity
@Table(name = "cliente"
        , catalog = "vendabd"
)
public class Cliente implements java.io.Serializable {


    private Long idCliente;
    private Endereco endereco;
    private String nome;
    private String telefone;
    private Set<Transacao> transacaos = new HashSet<Transacao>(0);

    public Cliente() {
    }


    public Cliente(Endereco endereco, String nome) {
        this.endereco = endereco;
        this.nome = nome;
    }

    public Cliente(Endereco endereco, String nome, String telefone, Set<Transacao> transacaos) {
        this.endereco = endereco;
        this.nome = nome;
        this.telefone = telefone;
        this.transacaos = transacaos;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)


    @Column(name = "idCliente", unique = true, nullable = false)
    public Long getIdCliente() {
        return this.idCliente;
    }

    public void setIdCliente(Long idCliente) {
        this.idCliente = idCliente;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "Endereco_idEndereco", nullable = false)
    public Endereco getEndereco() {
        return this.endereco;
    }

    public void setEndereco(Endereco endereco) {
        this.endereco = endereco;
    }


    @Column(name = "nome", nullable = false, length = 45)
    public String getNome() {
        return this.nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }


    @Column(name = "telefone", length = 45)
    public String getTelefone() {
        return this.telefone;
    }

    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "cliente")
    public Set<Transacao> getTransacaos() {
        return this.transacaos;
    }

    public void setTransacaos(Set<Transacao> transacaos) {
        this.transacaos = transacaos;
    }


}


