package bernardo.venda.pojo;
// Generated Feb 3, 2016 4:08:05 PM by Hibernate Tools 4.3.1


import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Definicao generated by hbm2java
 */
@Entity
@Table(name = "definicao"
        , catalog = "vendabd"
)
public class Definicao implements java.io.Serializable {


    private Integer idDefinicao;
    private Double valorDesconto;
    private Double valorVenda;
    private Boolean descontavel;
    private Boolean enviarRelatorios;
    private Boolean resumoFinanceiro;
    private Boolean movEstoque;
    private Boolean prodAbaixoEstoque;

    public Definicao() {
    }

    public Definicao(Double valorDesconto, Double valorVenda, Boolean descontavel, Boolean enviarRelatorios, Boolean resumoFinanceiro, Boolean movEstoque, Boolean prodAbaixoEstoque) {
        this.valorDesconto = valorDesconto;
        this.valorVenda = valorVenda;
        this.descontavel = descontavel;
        this.enviarRelatorios = enviarRelatorios;
        this.resumoFinanceiro = resumoFinanceiro;
        this.movEstoque = movEstoque;
        this.prodAbaixoEstoque = prodAbaixoEstoque;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)


    @Column(name = "idDefinicao", unique = true, nullable = false)
    public Integer getIdDefinicao() {
        return this.idDefinicao;
    }

    public void setIdDefinicao(Integer idDefinicao) {
        this.idDefinicao = idDefinicao;
    }


    @Column(name = "valorDesconto", precision = 22, scale = 0)
    public Double getValorDesconto() {
        return this.valorDesconto;
    }

    public void setValorDesconto(Double valorDesconto) {
        this.valorDesconto = valorDesconto;
    }


    @Column(name = "valorVenda", precision = 22, scale = 0)
    public Double getValorVenda() {
        return this.valorVenda;
    }

    public void setValorVenda(Double valorVenda) {
        this.valorVenda = valorVenda;
    }


    @Column(name = "descontavel")
    public Boolean getDescontavel() {
        return this.descontavel;
    }

    public void setDescontavel(Boolean descontavel) {
        this.descontavel = descontavel;
    }


    @Column(name = "enviarRelatorios")
    public Boolean getEnviarRelatorios() {
        return this.enviarRelatorios;
    }

    public void setEnviarRelatorios(Boolean enviarRelatorios) {
        this.enviarRelatorios = enviarRelatorios;
    }


    @Column(name = "resumo_financeiro")
    public Boolean getResumoFinanceiro() {
        return this.resumoFinanceiro;
    }

    public void setResumoFinanceiro(Boolean resumoFinanceiro) {
        this.resumoFinanceiro = resumoFinanceiro;
    }


    @Column(name = "mov_estoque")
    public Boolean getMovEstoque() {
        return this.movEstoque;
    }

    public void setMovEstoque(Boolean movEstoque) {
        this.movEstoque = movEstoque;
    }


    @Column(name = "prod_abaixo_estoque")
    public Boolean getProdAbaixoEstoque() {
        return this.prodAbaixoEstoque;
    }

    public void setProdAbaixoEstoque(Boolean prodAbaixoEstoque) {
        this.prodAbaixoEstoque = prodAbaixoEstoque;
    }


}


