package bernardo.venda.pojo;
// Generated Feb 3, 2016 4:08:05 PM by Hibernate Tools 4.3.1


import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Fornecedor generated by hbm2java
 */
@Entity
@Table(name = "fornecedor"
        , catalog = "vendabd"
        , uniqueConstraints = @UniqueConstraint(columnNames = "nome")
)
public class Fornecedor implements java.io.Serializable {


    private Long idFornecedor;
    private Endereco endereco;
    private String nome;
    private String telelfone;
    private String celular;
    private String email;
    private String observacao;
    private Set<Produto> produtos = new HashSet<Produto>(0);

    public Fornecedor() {
    }


    public Fornecedor(Endereco endereco, String nome) {
        this.endereco = endereco;
        this.nome = nome;
    }

    public Fornecedor(Endereco endereco, String nome, String telelfone, String celular, String email, String observacao, Set<Produto> produtos) {
        this.endereco = endereco;
        this.nome = nome;
        this.telelfone = telelfone;
        this.celular = celular;
        this.email = email;
        this.observacao = observacao;
        this.produtos = produtos;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)


    @Column(name = "idFornecedor", unique = true, nullable = false)
    public Long getIdFornecedor() {
        return this.idFornecedor;
    }

    public void setIdFornecedor(Long idFornecedor) {
        this.idFornecedor = idFornecedor;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "Endereco_idEndereco", nullable = false)
    @Cascade(CascadeType.ALL)
    public Endereco getEndereco() {
        return this.endereco;
    }

    public void setEndereco(Endereco endereco) {
        this.endereco = endereco;
    }


    @Column(name = "nome", unique = true, nullable = false, length = 45)
    public String getNome() {
        return this.nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }


    @Column(name = "telelfone", length = 45)
    public String getTelelfone() {
        return this.telelfone;
    }

    public void setTelelfone(String telelfone) {
        this.telelfone = telelfone;
    }


    @Column(name = "celular", length = 45)
    public String getCelular() {
        return this.celular;
    }

    public void setCelular(String celular) {
        this.celular = celular;
    }


    @Column(name = "email", length = 45)
    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }


    @Column(name = "observacao", length = 100)
    public String getObservacao() {
        return this.observacao;
    }

    public void setObservacao(String observacao) {
        this.observacao = observacao;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "fornecedor")
    public Set<Produto> getProdutos() {
        return this.produtos;
    }

    public void setProdutos(Set<Produto> produtos) {
        this.produtos = produtos;
    }


}


