package bernardo.venda.pojo;
// Generated Feb 3, 2016 4:08:05 PM by Hibernate Tools 4.3.1


import javax.persistence.*;
import java.util.Date;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Parcela generated by hbm2java
 */
@Entity
@Table(name = "parcela"
        , catalog = "vendabd"
)
public class Parcela implements java.io.Serializable {


    private Integer idParcela;
    private Transacao transacao;
    private Date data;
    private double valor;
    private String tipoPagamento;
    private String numerario;

    public Parcela() {
    }


    public Parcela(Transacao transacao, Date data, double valor, String tipoPagamento) {
        this.transacao = transacao;
        this.data = data;
        this.valor = valor;
        this.tipoPagamento = tipoPagamento;
    }

    public Parcela(Transacao transacao, Date data, double valor, String tipoPagamento, String numerario) {
        this.transacao = transacao;
        this.data = data;
        this.valor = valor;
        this.tipoPagamento = tipoPagamento;
        this.numerario = numerario;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)


    @Column(name = "idParcela", unique = true, nullable = false)
    public Integer getIdParcela() {
        return this.idParcela;
    }

    public void setIdParcela(Integer idParcela) {
        this.idParcela = idParcela;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "Transacao_idTransacao", nullable = false)
    public Transacao getTransacao() {
        return this.transacao;
    }

    public void setTransacao(Transacao transacao) {
        this.transacao = transacao;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "data", nullable = false, length = 19)
    public Date getData() {
        return this.data;
    }

    public void setData(Date data) {
        this.data = data;
    }


    @Column(name = "valor", nullable = false, precision = 22, scale = 0)
    public double getValor() {
        return this.valor;
    }

    public void setValor(double valor) {
        this.valor = valor;
    }


    @Column(name = "tipo_pagamento", nullable = false, length = 45)
    public String getTipoPagamento() {
        return this.tipoPagamento;
    }

    public void setTipoPagamento(String tipoPagamento) {
        this.tipoPagamento = tipoPagamento;
    }


    @Column(name = "numerario", length = 45)
    public String getNumerario() {
        return this.numerario;
    }

    public void setNumerario(String numerario) {
        this.numerario = numerario;
    }


}


