package bernardo.venda.pojo;
// Generated Feb 3, 2016 4:08:05 PM by Hibernate Tools 4.3.1


import javax.persistence.*;

/**
 * ProdutoVenda generated by hbm2java
 */
@Entity
@Table(name = "produto_venda"
        , catalog = "vendabd"
)
public class ProdutoVenda implements java.io.Serializable {


    private ProdutoVendaId id;
    private Produto produto;
    private Transacao transacao;
    private int quantidade;
    private Integer quantEntrada;
    private Integer quantSaida;

    public ProdutoVenda() {
    }


    public ProdutoVenda(ProdutoVendaId id, Produto produto, Transacao transacao, int quantidade) {
        this.id = id;
        this.produto = produto;
        this.transacao = transacao;
        this.quantidade = quantidade;
    }

    public ProdutoVenda(ProdutoVendaId id, Produto produto, Transacao transacao, int quantidade, Integer quantEntrada, Integer quantSaida) {
        this.id = id;
        this.produto = produto;
        this.transacao = transacao;
        this.quantidade = quantidade;
        this.quantEntrada = quantEntrada;
        this.quantSaida = quantSaida;
    }

    @EmbeddedId


    @AttributeOverrides({
            @AttributeOverride(name = "transacaoIdTransacao", column = @Column(name = "Transacao_idTransacao", nullable = false)),
            @AttributeOverride(name = "produtoIdProduto", column = @Column(name = "Produto_idProduto", nullable = false))})
    public ProdutoVendaId getId() {
        return this.id;
    }

    public void setId(ProdutoVendaId id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "Produto_idProduto", nullable = false, insertable = false, updatable = false)
    public Produto getProduto() {
        return this.produto;
    }

    public void setProduto(Produto produto) {
        this.produto = produto;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "Transacao_idTransacao", nullable = false, insertable = false, updatable = false)
    public Transacao getTransacao() {
        return this.transacao;
    }

    public void setTransacao(Transacao transacao) {
        this.transacao = transacao;
    }


    @Column(name = "quantidade_", nullable = false)
    public int getQuantidade() {
        return this.quantidade;
    }

    public void setQuantidade(int quantidade) {
        this.quantidade = quantidade;
    }


    @Column(name = "quant_entrada")
    public Integer getQuantEntrada() {
        return this.quantEntrada;
    }

    public void setQuantEntrada(Integer quantEntrada) {
        this.quantEntrada = quantEntrada;
    }


    @Column(name = "quant_saida")
    public Integer getQuantSaida() {
        return this.quantSaida;
    }

    public void setQuantSaida(Integer quantSaida) {
        this.quantSaida = quantSaida;
    }


}


