package bernardo.venda.pojo;
// Generated Feb 3, 2016 4:08:05 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProdutoVendaId generated by hbm2java
 */
@Embeddable
public class ProdutoVendaId implements java.io.Serializable {


    private long transacaoIdTransacao;
    private long produtoIdProduto;

    public ProdutoVendaId() {
    }

    public ProdutoVendaId(long transacaoIdTransacao, long produtoIdProduto) {
        this.transacaoIdTransacao = transacaoIdTransacao;
        this.produtoIdProduto = produtoIdProduto;
    }


    @Column(name = "Transacao_idTransacao", nullable = false)
    public long getTransacaoIdTransacao() {
        return this.transacaoIdTransacao;
    }

    public void setTransacaoIdTransacao(long transacaoIdTransacao) {
        this.transacaoIdTransacao = transacaoIdTransacao;
    }


    @Column(name = "Produto_idProduto", nullable = false)
    public long getProdutoIdProduto() {
        return this.produtoIdProduto;
    }

    public void setProdutoIdProduto(long produtoIdProduto) {
        this.produtoIdProduto = produtoIdProduto;
    }


    public boolean equals(Object other) {
        if ((this == other)) return true;
        if ((other == null)) return false;
        if (!(other instanceof ProdutoVendaId)) return false;
        ProdutoVendaId castOther = (ProdutoVendaId) other;

        return (this.getTransacaoIdTransacao() == castOther.getTransacaoIdTransacao())
                && (this.getProdutoIdProduto() == castOther.getProdutoIdProduto());
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (int) this.getTransacaoIdTransacao();
        result = 37 * result + (int) this.getProdutoIdProduto();
        return result;
    }


}


