package bernardo.venda.pojo;
// Generated Feb 3, 2016 4:08:05 PM by Hibernate Tools 4.3.1


import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;

import javax.persistence.*;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Transacao generated by hbm2java
 */
@Entity
@Table(name = "transacao"
        , catalog = "vendabd"
)
public class Transacao implements java.io.Serializable {


    private Long idTransacao;
    private Caixa caixa;
    private Cliente cliente;
    private Utilizador utilizador;
    private Date data;
    private Date hora;
    private double valor;
    private double desconto;
    private String tipo;
    private String cancelado;
    private String observacao;
    private String cancelador;
    private Date dataCancelada;
    private double valorFinal;
    private List<Parcela> parcelas = new ArrayList(0);
    private List<ProdutoVenda> produtoVendas = new ArrayList(0);

    public Transacao() {
    }


    public Transacao(Caixa caixa, Utilizador utilizador, Date data, double valor, double desconto, String tipo, String cancelado, double valorFinal) {
        this.caixa = caixa;
        this.utilizador = utilizador;
        this.data = data;
        this.valor = valor;
        this.desconto = desconto;
        this.tipo = tipo;
        this.cancelado = cancelado;
        this.valorFinal = valorFinal;
    }

    public Transacao(Caixa caixa, Cliente cliente, Utilizador utilizador, Date data, Date hora, double valor, double desconto, String tipo, String cancelado, String observacao, String cancelador, Date dataCancelada, double valorFinal, List<Parcela> parcelas, List<ProdutoVenda> produtoVendas) {
        this.caixa = caixa;
        this.cliente = cliente;
        this.utilizador = utilizador;
        this.data = data;
        this.hora = hora;
        this.valor = valor;
        this.desconto = desconto;
        this.tipo = tipo;
        this.cancelado = cancelado;
        this.observacao = observacao;
        this.cancelador = cancelador;
        this.dataCancelada = dataCancelada;
        this.valorFinal = valorFinal;
        this.parcelas = parcelas;
        this.produtoVendas = produtoVendas;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)


    @Column(name = "idTransacao", unique = true, nullable = false)
    public Long getIdTransacao() {
        return this.idTransacao;
    }

    public void setIdTransacao(Long idTransacao) {
        this.idTransacao = idTransacao;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "Caixa_idCaixa", nullable = false)
    public Caixa getCaixa() {
        return this.caixa;
    }

    public void setCaixa(Caixa caixa) {
        this.caixa = caixa;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "Cliente_idCliente")
    public Cliente getCliente() {
        return this.cliente;
    }

    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "Utilizador_idUtilizador", nullable = false)
    public Utilizador getUtilizador() {
        return this.utilizador;
    }

    public void setUtilizador(Utilizador utilizador) {
        this.utilizador = utilizador;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "data", nullable = false, length = 10)
    public Date getData() {
        return this.data;
    }

    public void setData(Date data) {
        this.data = data;
    }

    @Temporal(TemporalType.TIME)
    @Column(name = "hora", length = 8)
    public Date getHora() {
        return this.hora;
    }

    public void setHora(Date hora) {
        this.hora = hora;
    }


    @Column(name = "valor", nullable = false, precision = 22, scale = 0)
    public double getValor() {
        return this.valor;
    }

    public void setValor(double valor) {
        this.valor = valor;
    }


    @Column(name = "desconto", nullable = false, precision = 22, scale = 0)
    public double getDesconto() {
        return this.desconto;
    }

    public void setDesconto(double desconto) {
        this.desconto = desconto;
    }


    @Column(name = "tipo", nullable = false, length = 45)
    public String getTipo() {
        return this.tipo;
    }

    public void setTipo(String tipo) {
        this.tipo = tipo;
    }


    @Column(name = "cancelado", nullable = false, length = 45)
    public String getCancelado() {
        return this.cancelado;
    }

    public void setCancelado(String cancelado) {
        this.cancelado = cancelado;
    }


    @Column(name = "observacao", length = 100)
    public String getObservacao() {
        return this.observacao;
    }

    public void setObservacao(String observacao) {
        this.observacao = observacao;
    }


    @Column(name = "cancelador", length = 45)
    public String getCancelador() {
        return this.cancelador;
    }

    public void setCancelador(String cancelador) {
        this.cancelador = cancelador;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "data_cancelada", length = 10)
    public Date getDataCancelada() {
        return this.dataCancelada;
    }

    public void setDataCancelada(Date dataCancelada) {
        this.dataCancelada = dataCancelada;
    }


    @Column(name = "valor_final", nullable = false, precision = 22, scale = 0)
    public double getValorFinal() {
        return this.valorFinal;
    }

    public void setValorFinal(double valorFinal) {
        this.valorFinal = valorFinal;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "transacao")
    @Cascade(CascadeType.ALL)
    public List<Parcela> getParcelas() {
        return this.parcelas;
    }

    public void setParcelas(List<Parcela> parcelas) {
        this.parcelas = parcelas;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "transacao")
    public List<ProdutoVenda> getProdutoVendas() {
        return this.produtoVendas;
    }

    public void setProdutoVendas(List<ProdutoVenda> produtoVendas) {
        this.produtoVendas = produtoVendas;
    }


}


