package bernardo.venda.pojo;
// Generated Feb 3, 2016 4:08:05 PM by Hibernate Tools 4.3.1


import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Utilizador generated by hbm2java
 */
@Entity
@Table(name = "utilizador"
        , catalog = "vendabd"
)
public class Utilizador implements java.io.Serializable {


    private Integer idUtilizador;
    private String nomeCompleto;
    private String nomeUtilizador;
    private String senha;
    private String perfil;
    private Set<Transacao> transacaos = new HashSet<Transacao>(0);
    private Set<Caixa> caixas = new HashSet<Caixa>(0);

    public Utilizador() {
    }


    public Utilizador(String nomeCompleto, String nomeUtilizador, String senha, String perfil) {
        this.nomeCompleto = nomeCompleto;
        this.nomeUtilizador = nomeUtilizador;
        this.senha = senha;
        this.perfil = perfil;
    }

    public Utilizador(String nomeCompleto, String nomeUtilizador, String senha, String perfil, Set<Transacao> transacaos, Set<Caixa> caixas) {
        this.nomeCompleto = nomeCompleto;
        this.nomeUtilizador = nomeUtilizador;
        this.senha = senha;
        this.perfil = perfil;
        this.transacaos = transacaos;
        this.caixas = caixas;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)


    @Column(name = "idUtilizador", unique = true, nullable = false)
    public Integer getIdUtilizador() {
        return this.idUtilizador;
    }

    public void setIdUtilizador(Integer idUtilizador) {
        this.idUtilizador = idUtilizador;
    }


    @Column(name = "nome_completo", nullable = false, length = 100)
    public String getNomeCompleto() {
        return this.nomeCompleto;
    }

    public void setNomeCompleto(String nomeCompleto) {
        this.nomeCompleto = nomeCompleto;
    }


    @Column(name = "nome_utilizador", nullable = false, length = 20)
    public String getNomeUtilizador() {
        return this.nomeUtilizador;
    }

    public void setNomeUtilizador(String nomeUtilizador) {
        this.nomeUtilizador = nomeUtilizador;
    }


    @Column(name = "senha", nullable = false, length = 10)
    public String getSenha() {
        return this.senha;
    }

    public void setSenha(String senha) {
        this.senha = senha;
    }


    @Column(name = "perfil", nullable = false, length = 45)
    public String getPerfil() {
        return this.perfil;
    }

    public void setPerfil(String perfil) {
        this.perfil = perfil;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "utilizador")
    public Set<Transacao> getTransacaos() {
        return this.transacaos;
    }

    public void setTransacaos(Set<Transacao> transacaos) {
        this.transacaos = transacaos;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "utilizador")
    public Set<Caixa> getCaixas() {
        return this.caixas;
    }

    public void setCaixas(Set<Caixa> caixas) {
        this.caixas = caixas;
    }


}


