/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bernardo.venda.visao;

import bernardo.venda.controle.ProdutoVendaControle;
import bernardo.venda.pojo.Caixa;
import bernardo.venda.pojo.Movimento;
import bernardo.venda.pojo.Produto;
import bernardo.venda.pojo.Transacao;
import bernardo.venda.tablemodel.TabelaMovimento;
import bernardo.venda.util.Tarefa;
import bernardo.venda.util.Util;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperReport;

/**
 *
 * @author dalves
 */
public class CaixaTotal extends javax.swing.JDialog {

     private static ProdutoVendaControle pvc = new ProdutoVendaControle();
    private double totalFacturado;
    private double totalAdicionado;
    private double totalRetirado;
    private double totalVenda;
    private double totalLucro;
    private List<Movimento> listaMovimentos;
    private Caixa caixa;
    /**
     * Creates new form CaixaTotal
     */
    public CaixaTotal(java.awt.Window parent, String titulo) {
        super(parent, titulo);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        processamento = new org.jdesktop.swingx.JXBusyLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtValorTotalVendas = new javax.swing.JLabel();
        lbInicialCaixa = new javax.swing.JLabel();
        lbRetirado = new javax.swing.JLabel();
        lbAdicionado = new javax.swing.JLabel();
        lbFinal = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbNumeroCaixa = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lbDataHora = new javax.swing.JLabel();
        lbResponsavel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtObs = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaMovimento = new org.jdesktop.swingx.JXTable();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tLucro = new javax.swing.JLabel();
        tVendas = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Operações"));

        jButton2.setBackground(new java.awt.Color(246, 168, 168));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bernardo/venda/imagens/cancel-24.png"))); // NOI18N
        jButton2.setText("Fechar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnImprimir.setBackground(new java.awt.Color(165, 254, 160));
        btnImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bernardo/venda/imagens/Print.png"))); // NOI18N
        btnImprimir.setText("Imprimir");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        processamento.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(processamento, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnImprimir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addGap(8, 8, 8))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(0, 13, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnImprimir)
                            .addComponent(jButton2)))
                    .addComponent(processamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("Faturamento Total das Vendas:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("Saldo Inicial do Caixa:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("Valor Retirado:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("Valor Adicionado:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setText("Saldo Final:");

        txtValorTotalVendas.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtValorTotalVendas.setText("jLabel6");

        lbInicialCaixa.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lbInicialCaixa.setText("jLabel7");

        lbRetirado.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lbRetirado.setText("jLabel8");

        lbAdicionado.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lbAdicionado.setText("jLabel9");

        lbFinal.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lbFinal.setText("jLabel10");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel6.setText("Número do Caixa:");

        lbNumeroCaixa.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lbNumeroCaixa.setText("jLabel10");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtValorTotalVendas)
                                    .addComponent(lbInicialCaixa)
                                    .addComponent(lbRetirado)
                                    .addComponent(lbAdicionado)
                                    .addComponent(lbFinal)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbNumeroCaixa)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lbNumeroCaixa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtValorTotalVendas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lbInicialCaixa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lbRetirado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lbAdicionado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lbFinal))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel7.setText("Data e Hora de Abertura:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel8.setText("Utilizador Responsável:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel9.setText("Observaões:");

        lbDataHora.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lbDataHora.setText("jLabel11");

        lbResponsavel.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lbResponsavel.setText("jLabel12");

        txtObs.setColumns(20);
        txtObs.setRows(5);
        jScrollPane1.setViewportView(txtObs);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lbResponsavel)
                                .addGap(0, 657, Short.MAX_VALUE))
                            .addComponent(jScrollPane1)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbDataHora)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lbDataHora))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lbResponsavel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(0, 52, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Resumo Financeiro do Caixa", jPanel3);

        tabelaMovimento.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jScrollPane2.setViewportView(tabelaMovimento);

        jLabel10.setText("Total vendas:");

        jLabel11.setText("Total Lucro:");

        tLucro.setText("jLabel12");

        tVendas.setText("jLabel13");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(303, 303, 303)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tVendas)
                .addGap(85, 85, 85)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tLucro)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(tLucro)
                    .addComponent(tVendas))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Movimento de Produtos", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 969, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed

    }//GEN-LAST:event_btnImprimirActionPerformed

     public void inicializaTotais(List<Transacao> transacoes, Caixa c) {
        this.caixa = c;
        calculaTotais(transacoes);
        lbNumeroCaixa.setText(c.getIdCaixa() + "");
        lbResponsavel.setText(c.getUtilizador().getNomeCompleto());
        lbDataHora.setText(c.getDataAbertura() + "");
        txtObs.setText(c.getObservacao());
        txtValorTotalVendas.setText(Util.formatarMoeda(this.totalFacturado));
        lbInicialCaixa.setText(Util.formatarMoeda(c.getValorInicial()));
        lbAdicionado.setText(Util.formatarMoeda(this.totalAdicionado));
        lbRetirado.setText(Util.formatarMoeda(this.totalRetirado));
        lbFinal.setText(Util.formatarMoeda(this.totalFacturado + c.getValorInicial() + this.totalAdicionado - this.totalRetirado));
        actualizarMovimentos();
    }
    // End of variables declaration                   

    private void calculaTotais(List<Transacao> transacoes) {
        for (int i = 0; i < transacoes.size(); i++) {
            Transacao t = transacoes.get(i);
            if (!t.getCancelado().equals("Sim") && t.getTipo().equalsIgnoreCase("Venda")) {
                this.totalFacturado += t.getValorFinal();
            } else if (!t.getCancelado().equals("Sim") && t.getTipo().equalsIgnoreCase("Sangria de Caixa")) {
                this.totalRetirado += t.getValorFinal();
            } else if (!t.getCancelado().equals("Sim") && t.getTipo().equalsIgnoreCase("Suprimento de Caixa")) {
                this.totalAdicionado += t.getValorFinal();
            }
        }
    }

    private void actualizarMovimentos() {
        this.listaMovimentos = new ArrayList<>();
        List t1 = pvc.findAllM(this.caixa);
        for (Object t : t1) {
            Object[] o = (Object[]) t;
            Produto p = (Produto) o[0];
            long qVendida = (long) o[1];
            long entrada = 0;
            long saida = 0;
            if (o[2] != null)
                entrada = (long) o[2];
            if (o[3] != null)
                saida = (long) o[3];
            Integer estoque = p.getQuantidadeActual();
            String produto = p.getDescricao();
            double vendas = qVendida * p.getPrecoVenda();
            double lucro = qVendida * (p.getPrecoVenda() - p.getPrecoCompra());
            this.totalVenda += vendas;
            this.totalLucro += lucro;
            Movimento m = new Movimento(produto, entrada, saida, qVendida, vendas, lucro, estoque);
            listaMovimentos.add(m);
        }
        tabelaMovimento.setModel(new TabelaMovimento(listaMovimentos));
        tabelaMovimento.getColumnModel().getColumn(0).setMinWidth(350);
        tabelaMovimento.getColumnModel().getColumn(1).setMaxWidth(60);
        tabelaMovimento.getColumnModel().getColumn(2).setMaxWidth(60);
        tabelaMovimento.getColumnModel().getColumn(3).setMaxWidth(60);
        tabelaMovimento.getColumnModel().getColumn(6).setMaxWidth(60);
        tLucro.setText(Util.formatarMoeda(totalLucro));
        tVendas.setText(Util.formatarMoeda(totalVenda));
    }

    private void relatorioProdutos(String titulo) {
        try {
            btnImprimir.setEnabled(false);
            processamento.setBusy(true);
            String caminho = "relatorios/report_product.jrxml";
            JasperReport jasper = JasperCompileManager.compileReport(caminho);
            Map<String, Object> parametros;
            List<Map<?, ?>> list = new ArrayList<>(0);
            for (int i = 0; i < listaMovimentos.size(); i++) {
                parametros = new HashMap<>();
                parametros.put("produto", listaMovimentos.get(i).getProduto());
                parametros.put("entrada", listaMovimentos.get(i).getEntrada());
                parametros.put("saida", listaMovimentos.get(i).getSaida());
                parametros.put("vendas", listaMovimentos.get(i).getqVendida());
                parametros.put("valor_vendas", listaMovimentos.get(i).getVendas());
                parametros.put("lucro", listaMovimentos.get(i).getLucro());
                parametros.put("estoque", listaMovimentos.get(i).getEstoque());
                parametros.put("loja", "Loja Teste 1");
                parametros.put("titulo", "" + titulo + "");
                parametros.put("endereco", "Avenida Bernardo Alves Maluleque nº2016");
                list.add(parametros);
            }
            Tarefa t = new Tarefa(processamento, btnImprimir, jasper, list);
            t.execute();
            processamento.setText(null);
        } catch (JRException ex) {
            JOptionPane.showMessageDialog(this, "Ocorreu um erro", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbAdicionado;
    private javax.swing.JLabel lbDataHora;
    private javax.swing.JLabel lbFinal;
    private javax.swing.JLabel lbInicialCaixa;
    private javax.swing.JLabel lbNumeroCaixa;
    private javax.swing.JLabel lbResponsavel;
    private javax.swing.JLabel lbRetirado;
    private org.jdesktop.swingx.JXBusyLabel processamento;
    private javax.swing.JLabel tLucro;
    private javax.swing.JLabel tVendas;
    private org.jdesktop.swingx.JXTable tabelaMovimento;
    private javax.swing.JTextArea txtObs;
    private javax.swing.JLabel txtValorTotalVendas;
    // End of variables declaration//GEN-END:variables
}
