/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bernardo.venda.visao;

import bernardo.venda.controle.CaixaControle;
import bernardo.venda.controle.ProdutoControle;
import bernardo.venda.controle.ProdutoVendaControle;
import bernardo.venda.controle.TransacaoControle;
import bernardo.venda.pojo.Caixa;
import bernardo.venda.pojo.Produto;
import bernardo.venda.pojo.ProdutoVenda;
import bernardo.venda.pojo.Transacao;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author dalves
 */
public class ObservacaoView extends javax.swing.JDialog {

    private Transacao transacao;
    private TransacaoControle transControle = new TransacaoControle();
    private CaixaControle caixaControle = new CaixaControle();
    private ProdutoControle pc = new ProdutoControle();
    private ProdutoVendaControle pvControle = new ProdutoVendaControle();
    /**
     * Creates new form ObservacaoView
     */
    public ObservacaoView(java.awt.Window parent, String tit) {
        super(parent, tit);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtObs = new org.jdesktop.swingx.JXTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Observações(Não obrigatório)");

        txtObs.setColumns(20);
        txtObs.setLineWrap(true);
        txtObs.setRows(5);
        txtObs.setPrompt("Escreva o uma observação sobre o Cancelamento da transação");
        jScrollPane1.setViewportView(txtObs);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bernardo/venda/imagens/Save.png"))); // NOI18N
        jButton1.setText("Continuar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bernardo/venda/imagens/Cancel 2_1.png"))); // NOI18N
        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        continuarCancelamento();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    void setTransacao(Transacao t) {
        this.transacao = t;
    }

    private void continuarCancelamento() {
        transacao.setCancelado("Sim");
        Long cod = transacao.getIdTransacao();
        transacao.setDataCancelada(new Date());
        transacao.setCancelador(MainView.utilizadorLogado.getNomeUtilizador());
        transacao.setObservacao(txtObs.getText());
        if (transControle.atualizar(transacao) != null) {
            transacao = transControle.findById("idTransacao", cod);
            retirarValorCaixa();
            reporEstoque();
            JOptionPane.showMessageDialog(rootPane, "Cancelamento Efectuado!", "Cancelamento de Transacao", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
        }
    }

    private void retirarValorCaixa() {
        double valorActual = transacao.getCaixa().getValorFinal();
        double valorTransa = transacao.getValorFinal();
        Caixa c = transacao.getCaixa();
        c.setValorFinal(valorActual + valorTransa);
        caixaControle.atualizar(c);
    }

    private void reporEstoque() {
        List<ProdutoVenda> pv = pvControle.findAll(transacao);
        for (int i = 0; i < pv.size(); i++) {
            Produto p = pv.get(i).getProduto();
            int quant = pv.get(i).getQuantidade();
            int quantAct = p.getQuantidadeActual();
            p.setQuantidadeActual(quant + quantAct);
            pc.atualizar(p);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private org.jdesktop.swingx.JXTextArea txtObs;
    // End of variables declaration//GEN-END:variables
}
