/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bernardo.venda.visao;

import bernardo.venda.controle.CategoriaControle;
import bernardo.venda.controle.FornecedorControle;
import bernardo.venda.controle.ProdutoControle;
import bernardo.venda.pojo.Categoria;
import bernardo.venda.pojo.Fornecedor;
import bernardo.venda.pojo.Produto;
import bernardo.venda.util.HighlightListener;
import bernardo.venda.util.Icone;
import bernardo.venda.util.Util;
import bernardo.venda.util.ValidarCampo;
import bernardo.venda.util.ValidarCampoDouble;
import bernardo.venda.util.ValidarNumeroString;
import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.Window;
import java.awt.event.ItemEvent;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.text.ParseException;
import java.util.Date;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author dalves
 */
public class RegistoProdutoView extends javax.swing.JDialog {

     private static CategoriaControle cc = new CategoriaControle();
    private static FornecedorControle fornecedorControle = new FornecedorControle();
    ProdutoControle cp = new ProdutoControle();
    private Categoria categoria;
    private Produto produto;
    private Fornecedor fornecedor;
    private JFileChooser escolheFoto;
    private byte[] foto = null;
    private BufferedImage imagemBuffered;
    /**
     * Creates new form RegistoProdutoView
     */
    public RegistoProdutoView(java.awt.Window parent, String title) {
        super(parent, title);
        initComponents();
        validarCampos();
        preecheCategorias();
        preecheFornecedores();
    }
    
    public static void preecheCategorias() {
        Util.preencheComboBox(cmbxCategoria, cc.categorias());
    }

    public static void preecheFornecedores() {
        Util.preencheComboBox(cmbxFornecedor, fornecedorControle.fornecedoresNomes());
    }

    static void setCategoriaEscolhida(Categoria c) {
        cmbxCategoria.setSelectedItem(c.getDescricao());
    }
    
    static void setFornecedorEscolhido(Fornecedor c) {
        cmbxFornecedor.setSelectedItem(c.getNome());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtNomeDescricao = new org.jdesktop.swingx.JXTextField();
        txtCodBarras = new javax.swing.JTextField();
        cmbxCategoria = new javax.swing.JComboBox<>();
        txtVCompra = new javax.swing.JTextField();
        txtValorVenda = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        lbLucro = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtQActual = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtObservacao = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        cmbxFornecedor = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        btnNovoForn = new javax.swing.JButton();
        txtEstoqueMin = new javax.swing.JTextField();
        txtEstoqueMax = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jXHyperlink1 = new org.jdesktop.swingx.JXHyperlink();
        lbFoto = new javax.swing.JLabel();
        jXHyperlink2 = new org.jdesktop.swingx.JXHyperlink();
        jPanel6 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados do Produto"));
        jPanel5.setForeground(new java.awt.Color(57, 57, 57));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("<html><b><font color=red>*</font></b> Nome/Descrição:</html>");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("<html><b><font color=red>*</font></b> Código de Barras:</html>");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("<html><b><font color=red>*</font></b> Categoria:</html>");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("<html><b><font color=red>*</font></b> Preço de Compra:</html>");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("<html><b><font color=red>*</font></b> Preço de Venda:</html>");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel12.setText("Margem de Lucro:");

        txtNomeDescricao.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txtNomeDescricao.setPrompt("EX:NUTRIDAY FRUIT STRAWBERRY 600G");
        txtNomeDescricao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNomeDescricaoKeyTyped(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNomeDescricaoKeyReleased(evt);
            }
        });

        txtCodBarras.setBackground(new java.awt.Color(166, 250, 175));
        txtCodBarras.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txtCodBarras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodBarrasActionPerformed(evt);
            }
        });
        txtCodBarras.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCodBarrasKeyReleased(evt);
            }
        });

        cmbxCategoria.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        cmbxCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbxCategoria.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbxCategoriaItemStateChanged(evt);
            }
        });
        cmbxCategoria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cmbxCategoriaKeyReleased(evt);
            }
        });

        txtVCompra.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txtVCompra.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtVCompra.setToolTipText("Valor da compra por unidade");
        txtVCompra.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtVCompraFocusLost(evt);
            }
        });
        txtVCompra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtVCompraKeyReleased(evt);
            }
        });

        txtValorVenda.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txtValorVenda.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtValorVenda.setToolTipText("Valor de venda por unidade");
        txtValorVenda.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtValorVendaFocusLost(evt);
            }
        });
        txtValorVenda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtValorVendaKeyReleased(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jButton5.setText("Nova");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("<html><b><font color=red>*</font></b> Unidade de Medida:</html>");

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "UN", "KG", "LT", "LATA", "METRO", "CAIXA", "EMBALAGEM", "COPO", " " }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        lbLucro.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lbLucro.setText("0");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbxCategoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(txtCodBarras, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(txtVCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(txtValorVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12)
                                        .addComponent(jLabel12)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox1, 0, 156, Short.MAX_VALUE)
                                    .addComponent(lbLucro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(12, 12, 12)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtNomeDescricao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtCodBarras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtNomeDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cmbxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtVCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel6)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtValorVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(lbLucro))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Estoque e Fornecedor"));
        jPanel4.setForeground(new java.awt.Color(57, 57, 57));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("<html><b><font color=red>*</font></b> Estoque Min:</html>");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("<html><b><font color=red>*</font></b> Estoque Actual:</html>");

        txtQActual.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txtQActual.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtQActual.setText("0");
        txtQActual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQActualActionPerformed(evt);
            }
        });
        txtQActual.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtQActualKeyReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel3.setText("Observações:");

        txtObservacao.setColumns(20);
        txtObservacao.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txtObservacao.setRows(5);
        txtObservacao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtObservacaoKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(txtObservacao);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel4.setText("Estoque Max:");

        cmbxFornecedor.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        cmbxFornecedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbxFornecedor.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbxFornecedorItemStateChanged(evt);
            }
        });
        cmbxFornecedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cmbxFornecedorKeyReleased(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel13.setText("Fornecedor:");

        btnNovoForn.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        btnNovoForn.setText("Novo");
        btnNovoForn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoFornActionPerformed(evt);
            }
        });

        txtEstoqueMin.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtEstoqueMin.setText("0");

        txtEstoqueMax.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtEstoqueMax.setText("0");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEstoqueMin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtQActual, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEstoqueMax, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel13)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(cmbxFornecedor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnNovoForn))
                            .addComponent(jScrollPane1))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtQActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(txtEstoqueMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEstoqueMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(cmbxFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNovoForn))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bernardo/venda/imagens/New Product.png"))); // NOI18N
        jLabel5.setText("Registo de Produtos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Foto do Produto"));

        jXHyperlink1.setText("Carregar Foto");
        jXHyperlink1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXHyperlink1ActionPerformed(evt);
            }
        });

        jXHyperlink2.setText("Limpar Foto");
        jXHyperlink2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXHyperlink2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jXHyperlink1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jXHyperlink2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(lbFoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(lbFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jXHyperlink1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXHyperlink2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Operações"));

        jButton1.setBackground(new java.awt.Color(246, 168, 168));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bernardo/venda/imagens/cancel-24.png"))); // NOI18N
        jButton1.setText("Fechar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnGuardar.setBackground(new java.awt.Color(165, 254, 160));
        btnGuardar.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bernardo/venda/imagens/ok-24.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        jLabel14.setText("<html><b><font color=red>* Campos Obrigatórios</font></b</html>");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btnGuardar))
                .addGap(0, 9, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(1, 1, 1)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeDescricaoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeDescricaoKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            cmbxCategoria.requestFocus();
        }
    }//GEN-LAST:event_txtNomeDescricaoKeyReleased

    private void txtNomeDescricaoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeDescricaoKeyTyped

        Util.toUpperCase(evt);
    }//GEN-LAST:event_txtNomeDescricaoKeyTyped

    private void txtCodBarrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodBarrasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodBarrasActionPerformed

    private void txtCodBarrasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodBarrasKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtNomeDescricao.requestFocus();
        }
    }//GEN-LAST:event_txtCodBarrasKeyReleased

    private void cmbxCategoriaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbxCategoriaItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            Categoria c = cc.buscaPorNome(cmbxCategoria.getSelectedItem().toString());
            setCategoria(c);
        }
    }//GEN-LAST:event_cmbxCategoriaItemStateChanged

    private void cmbxCategoriaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbxCategoriaKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtVCompra.requestFocus();
        }
    }//GEN-LAST:event_cmbxCategoriaKeyReleased

    private void txtVCompraFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtVCompraFocusLost
        calculaLucro();
    }//GEN-LAST:event_txtVCompraFocusLost

    private void txtVCompraKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVCompraKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtValorVenda.requestFocus();
        }
    }//GEN-LAST:event_txtVCompraKeyReleased

    private void txtValorVendaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtValorVendaFocusLost
        calculaLucro();
    }//GEN-LAST:event_txtValorVendaFocusLost

    private void txtValorVendaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorVendaKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtQActual.requestFocus();
        }
    }//GEN-LAST:event_txtValorVendaKeyReleased

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Window pai = SwingUtilities.getWindowAncestor(this);
        CategoriaView rg = new CategoriaView(pai, "Categorias de Produtos");
        rg.setModal(true);
        rg.setLocationRelativeTo(null);
        rg.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void txtQActualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQActualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQActualActionPerformed

    private void txtQActualKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQActualKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtEstoqueMin.requestFocus();
        }
    }//GEN-LAST:event_txtQActualKeyReleased

    private void txtObservacaoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtObservacaoKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnGuardar.requestFocus();
            if (this.produto == null) {
                guardarProduto();
            } else {
                actualizarProduto(this.produto);
            }
            txtCodBarras.requestFocus();
        }
    }//GEN-LAST:event_txtObservacaoKeyReleased

    private void cmbxFornecedorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbxFornecedorItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            if (cmbxFornecedor.getSelectedIndex() != 0) {
                Fornecedor f = fornecedorControle.buscaPorNome(cmbxFornecedor.getSelectedItem().toString());
                this.fornecedor = f;
            }
        }
    }//GEN-LAST:event_cmbxFornecedorItemStateChanged

    private void cmbxFornecedorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbxFornecedorKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbxFornecedorKeyReleased

    private void btnNovoFornActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoFornActionPerformed
        Window pai = SwingUtilities.getWindowAncestor(this);
        System.out.println(this.getName());
        RegistoFornecedorView rg = new RegistoFornecedorView(pai, "Fornecedores");
        rg.setModal(true);
        rg.setPai(this.getName());
        rg.setLocationRelativeTo(null);
        rg.setVisible(true);
    }//GEN-LAST:event_btnNovoFornActionPerformed

    private void jXHyperlink1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXHyperlink1ActionPerformed
        escolheFoto = new JFileChooser();
        escolheFoto.setDialogTitle("Carregar a Foto do Produto");
        escolheFoto.setFileSelectionMode(JFileChooser.FILES_ONLY);
        escolheFoto.setCurrentDirectory(null);
        if (escolheFoto.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            try {
                lbFoto.setIcon(redimensionaImgem(new File(escolheFoto.getSelectedFile().getPath()), lbFoto.getWidth(), lbFoto.getHeight()));
                imagemBuffered = ImageIO.read(new File(escolheFoto.getSelectedFile().getPath()));
            } catch (IOException ex) {
                JOptionPane.showInternalMessageDialog(this, "Ocorreu um erro ao carregar a foto", "Carregar Foto", JOptionPane.ERROR_MESSAGE, Icone.ERRO);
            }
        }
    }//GEN-LAST:event_jXHyperlink1ActionPerformed

    private void jXHyperlink2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXHyperlink2ActionPerformed
        lbFoto.setIcon(null);
        produto.setFoto(null);
        imagemBuffered = null;
    }//GEN-LAST:event_jXHyperlink2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (this.produto == null)
        guardarProduto();
        else
        actualizarProduto(this.produto);
    }//GEN-LAST:event_btnGuardarActionPerformed

   private void guardarProduto() {

        String codigoBarras = null;
        String nome = null;
        String observacao = null;
        double precoCompra = 0;
        double precoVenda = 0;
        int quantidadeMin = 0;
        Integer quantidadeMax = null;
        int quantidadeActual = 0;

        if (estaPreenchido()) {
            try {
                codigoBarras = txtCodBarras.getText();
                nome = txtNomeDescricao.getText();
                observacao = txtObservacao.getText();
                quantidadeMin = Util.convertStringEmInteiro(txtEstoqueMin.getText());
                quantidadeMax = Util.convertStringEmInteiro(txtEstoqueMax.getText());
                quantidadeActual = Util.convertStringEmInteiro(txtQActual.getText());
                precoVenda = Util.convertStringEmDouble(txtValorVenda.getText());
                precoCompra = Util.convertStringEmDouble(txtVCompra.getText());
                produto = new Produto(categoria, nome, precoCompra, precoVenda, quantidadeMin, quantidadeActual);
                produto.setCodigoBarras(codigoBarras);
                produto.setObservacao(observacao);
                produto.setFornecedor(this.fornecedor);
                produto.setQuantidadeMax(quantidadeMax);
                produto.setFoto(converteImagem());
                if (jComboBox1.getSelectedItem() != null)
                    produto.setUnidadeMedida(jComboBox1.getSelectedItem().toString());

                if (cp.guardar(produto) != null) {
                    JOptionPane.showMessageDialog(rootPane, "Produto Registado!", "Informação", 1, Icone.INFORMACAO);
                    ProdutoView.actualizarTabelaProduto();
                    limparCampos();
                    produto = null;
                } else {
                    JOptionPane.showMessageDialog(this, "Ocorreu um erro ao guardar", "Erro", JOptionPane.ERROR_MESSAGE, Icone.ERRO);
                }

            } catch (ParseException ex) {
                JOptionPane.showMessageDialog(rootPane, "Verifique os dados informados", "Erro de dados", JOptionPane.ERROR_MESSAGE, Icone.ERRO);
            }
        }
    }

    private Categoria getCategoria() {
        return this.categoria;
    }

    void setCategoria(Categoria c) {
        this.categoria = c;
    }

    private boolean estaEmDia(Date date) {
        long diferencaDatas = (date.getTime()) - new Date().getTime() / (1000 * 60 * 60 * 24);
        return diferencaDatas > 7;
    }

    public void preencheCampos(Produto p) {
        this.produto = p;
        txtCodBarras.setText(p.getCodigoBarras().toUpperCase());
        txtNomeDescricao.setText(p.getDescricao().toUpperCase());
        txtVCompra.setText(repor(p.getPrecoCompra() + ""));
        txtValorVenda.setText(repor(p.getPrecoVenda() + ""));
        lbLucro.setText(repor((p.getPrecoVenda() - p.getPrecoCompra()) + ""));
        txtEstoqueMin.setText(p.getQuantidadeMin() + "");
        cmbxCategoria.setSelectedItem(p.getCategoria().getDescricao());
        if (p.getFornecedor() != null)
            cmbxFornecedor.setSelectedItem(p.getFornecedor().getNome());
        if (p.getFoto() != null)
            lbFoto.setIcon(redimensionaImgem(criaFile(p.getFoto()), lbFoto.getWidth(), lbFoto.getHeight()));
        jComboBox1.setSelectedItem(p.getUnidadeMedida());
        txtQActual.setText(p.getQuantidadeActual() + "");
        txtObservacao.setText(p.getObservacao() + "");

    }

    public void clonarProduto(Produto p) {
        txtCodBarras.setText(p.getCodigoBarras().toUpperCase());
        txtCodBarras.selectAll();
        txtNomeDescricao.setText("");
        txtVCompra.setText(repor(p.getPrecoCompra() + ""));
        txtValorVenda.setText(repor(p.getPrecoVenda() + ""));
        lbLucro.setText(repor((p.getPrecoVenda() - p.getPrecoCompra()) + ""));
        txtEstoqueMin.setText(p.getQuantidadeMin() + "");
        cmbxCategoria.setSelectedItem(p.getCategoria().getDescricao());
        if (p.getFornecedor() != null)
            cmbxFornecedor.setSelectedItem(p.getFornecedor().getNome());
        if (p.getFoto() != null)
            lbFoto.setIcon(redimensionaImgem(criaFile(p.getFoto()), lbFoto.getWidth(), lbFoto.getHeight()));
        jComboBox1.setSelectedItem(p.getUnidadeMedida());
        txtQActual.setText(p.getQuantidadeActual() + "");
        txtObservacao.setText(p.getObservacao() + "");

    }

    public String repor(String s) {
        return s.replace(".", ",");
    }

    private void limparCampos() {
        txtCodBarras.setText(null);
        txtNomeDescricao.setText(null);
        txtVCompra.setText(null);
        txtValorVenda.setText(null);
        lbLucro.setText(null);
        txtEstoqueMin.setText(null);
        txtQActual.setText(null);
        txtObservacao.setText(null);
        cmbxCategoria.setSelectedIndex(0);
        txtCodBarras.requestFocus();
        lbFoto.setIcon(null);
        jComboBox1.setSelectedIndex(0);
    }

    private boolean estaPreenchido() {
        if (txtNomeDescricao.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Informe o nome do produto");
            txtNomeDescricao.requestFocus();
            return false;
        }

        if (txtEstoqueMin.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Informe o estoque minimo");
            txtNomeDescricao.requestFocus();
            return false;
        }

        if (txtQActual.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Informe o estoque actual");
            txtQActual.requestFocus();
            return false;
        }

        if (txtVCompra.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Informe o preço do produto");
            txtVCompra.requestFocus();
            return false;
        }

        if (txtValorVenda.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Informe o custo do produto");
            txtValorVenda.requestFocus();
            return false;
        }
        return true;
    }

    private void actualizarProduto(Produto p) {
        if (estaPreenchido()) {
            try {
                p.setCategoria(categoria);
                p.setFornecedor(fornecedor);
                p.setQuantidadeMax(Util.convertStringEmInteiro(txtEstoqueMax.getText()));
                p.setCodigoBarras(txtCodBarras.getText());
                p.setDescricao(txtNomeDescricao.getText());
                p.setObservacao(txtObservacao.getText());
                p.setPrecoCompra(Util.convertStringEmDouble(txtVCompra.getText()));
                p.setPrecoVenda(Util.convertStringEmDouble(txtValorVenda.getText()));
                p.setQuantidadeActual(Util.convertStringEmInteiro(txtQActual.getText()));
                p.setQuantidadeMin(Util.convertStringEmInteiro(txtEstoqueMin.getText()));
                p.setFoto(converteImagem());
                if (jComboBox1.getSelectedItem() != null)
                    p.setUnidadeMedida(jComboBox1.getSelectedItem().toString());
                if (cp.atualizar(p) != null) {
                    JOptionPane.showMessageDialog(rootPane, "Produto actualizado!", "Informação", 1, Icone.INFORMACAO);
                    produto = null;
                    ProdutoView.actualizarTabelaProduto();
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "Ocorreu um erro ao actualizar", "Erro", JOptionPane.ERROR_MESSAGE, Icone.ERRO);
                }

            } catch (ParseException ex) {
                JOptionPane.showMessageDialog(this, "Verifique os dados informados", "Erro", JOptionPane.ERROR_MESSAGE, Icone.ERRO);
            }
        }
    }

    private void calculaLucro() {
        try {
            if (!txtValorVenda.getText().trim().isEmpty() && !txtVCompra.getText().trim().isEmpty()) {
                double preco = Util.convertStringEmDouble(txtValorVenda.getText());
                double custo = Util.convertStringEmDouble(txtVCompra.getText());
                if (preco > custo) {
                    lbLucro.setForeground(new Color(41, 127, 1));
                    lbLucro.setText(((preco - custo) + "").replace(".", ","));
                } else {
                    lbLucro.setForeground(new Color(228, 9, 14));
                    lbLucro.setText(((preco - custo) + "").replace(".", ","));
                }
            }
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this, "Verifique o preço e o custo", "Erro", JOptionPane.ERROR_MESSAGE, Icone.ERRO);
        }


    }

    private void validarCampos() {
        txtQActual.setDocument(new ValidarCampo(5));
        txtEstoqueMin.setDocument(new ValidarCampo(5));
        txtNomeDescricao.setDocument(new ValidarNumeroString(45));
        txtVCompra.setDocument(new ValidarCampoDouble(10));
        txtValorVenda.setDocument(new ValidarCampoDouble(10));
        
    }


    // Metodo para redimensionar a imagem
    private ImageIcon redimensionaImgem(File image, int new_w, int new_h) {
        try {
            BufferedImage imagem = ImageIO.read(image);
            BufferedImage new_img = new BufferedImage(new_w, new_h, BufferedImage.TYPE_INT_RGB);
            Graphics2D g = new_img.createGraphics();
            g.drawImage(imagem, 0, 0, new_w, new_h, null);
            g.dispose();
            return new ImageIcon(new_img);
        } catch (IOException ex) {
            throw new RuntimeException(ex);
        }
    }

    public byte[] converteImagem() {
        try {
            //OBTEM A IMAGEM E TRANSFORMA EM BYTES[]
            ByteArrayOutputStream bytesImg = new ByteArrayOutputStream();
            if (imagemBuffered == null) {//para caso de update, quando nao se altera a foto nao existe caminho
                foto = this.produto.getFoto();
                return foto;
            }
            ImageIO.write((BufferedImage) imagemBuffered, "jpg", bytesImg);//configura a imagem para bytesImg
            bytesImg.flush();//limpa a variável
            foto = bytesImg.toByteArray();//Converte ByteArrayOutputStream para byte[]
            bytesImg.close();//fecha a conversão
            //foto = ((DataBufferByte)((BufferedImage)imagem).getRaster().getDataBuffer()).getData();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Erro na Foto", "Foto", JOptionPane.ERROR_MESSAGE);
        }
        return foto;
    }


    private File criaFile(byte[] foto) {
        FileOutputStream fl = null;
        try {
            // lbFoto.setIcon(new ImageIcon(inst.getLogotipo()));
            File f = new File("img.png");
            fl = new FileOutputStream(f);
            fl.write(foto);
            fl.close();
            return f;
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Foto nao encontrada", "Foto", JOptionPane.ERROR_MESSAGE);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Erro na Foto", "Foto", JOptionPane.ERROR_MESSAGE);
        } finally {

        }
        return null;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNovoForn;
    public static javax.swing.JComboBox<String> cmbxCategoria;
    public static javax.swing.JComboBox<String> cmbxFornecedor;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private org.jdesktop.swingx.JXHyperlink jXHyperlink1;
    private org.jdesktop.swingx.JXHyperlink jXHyperlink2;
    private javax.swing.JLabel lbFoto;
    private javax.swing.JLabel lbLucro;
    private javax.swing.JTextField txtCodBarras;
    private javax.swing.JTextField txtEstoqueMax;
    private javax.swing.JTextField txtEstoqueMin;
    private org.jdesktop.swingx.JXTextField txtNomeDescricao;
    private javax.swing.JTextArea txtObservacao;
    private javax.swing.JTextField txtQActual;
    private javax.swing.JTextField txtVCompra;
    private javax.swing.JTextField txtValorVenda;
    // End of variables declaration//GEN-END:variables
}
