/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bernardo.venda.visao;

import bernardo.venda.controle.CaixaControle;
import bernardo.venda.controle.TransacaoControle;
import bernardo.venda.pojo.Transacao;
import bernardo.venda.util.Icone;
import bernardo.venda.util.Util;
import java.awt.event.KeyEvent;
import java.text.ParseException;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author dalves
 */
public class SangriaSuprimento extends javax.swing.JDialog {

    private CaixaControle caixaControle = new CaixaControle();
    private TransacaoControle transControle = new TransacaoControle();
    private boolean isSuprimento;
    /**
     * Creates new form SangriaSuprimento
     */
    public SangriaSuprimento(java.awt.Window parent, String titulo) {
        super(parent, titulo);
        initComponents();
        txtValor.selectAll();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtObs = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel1.setText("Valor:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel2.setText("Observação:");

        txtValor.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txtValor.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtValor.setText("0,00");
        txtValor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtValorKeyReleased(evt);
            }
        });

        txtObs.setColumns(20);
        txtObs.setLineWrap(true);
        txtObs.setRows(5);
        txtObs.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtObsKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(txtObs);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Operações"));

        jButton2.setBackground(new java.awt.Color(246, 168, 168));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bernardo/venda/imagens/cancel-24.png"))); // NOI18N
        jButton2.setText("Fechar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnGuardar.setBackground(new java.awt.Color(165, 254, 160));
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bernardo/venda/imagens/ok-24.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addGap(8, 8, 8))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(btnGuardar))
                .addGap(0, 4, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtValorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
        txtObs.requestFocus();
    }//GEN-LAST:event_txtValorKeyReleased

    private void txtObsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtObsKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnGuardar.requestFocus();
            if (isSuprimento) {
                suprimento();
            } else {
                sangria();
            }
        }
    }//GEN-LAST:event_txtObsKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (isSuprimento)
        suprimento();
        else
        sangria();
    }//GEN-LAST:event_btnGuardarActionPerformed

     private void sangria() {
        try {
            double valor = Util.convertStringEmDouble(txtValor.getText());
            if (valor > 0.00) {
                Transacao t = new Transacao(CaixaPane.caixa, MainView.utilizadorLogado, new Date(), valor, 0.0, "Sangria de Caixa", "não", valor);
                t.setHora(new Date());
                t.setObservacao(txtObs.getText());
                if (transControle.guardar(t) != null) {
                    JOptionPane.showMessageDialog(rootPane, "Sangria Efectuada!", "Informação", JOptionPane.INFORMATION_MESSAGE, Icone.INFORMACAO);
                    CaixaPane.actualizarTabela();
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Ocorreu um erro ao efectuar a Sangria", "Erro", JOptionPane.ERROR_MESSAGE, Icone.ERRO);
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Informe o valor", "Erro", 1, Icone.INFORMACAO);
            }

        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(rootPane, "Informe um valor válido\n" + ex, "Informação", JOptionPane.INFORMATION_MESSAGE, Icone.INFORMACAO);
        }
    }


    private void suprimento() {
        try {
            double valor = Util.convertStringEmDouble(txtValor.getText());
            if (valor > 0) {
                Transacao t = new Transacao(CaixaPane.caixa, MainView.utilizadorLogado, new Date(), valor, 0.0, "Suprimento de Caixa", "não", valor);
                t.setHora(new Date());
                t.setObservacao(txtObs.getText());
                if (transControle.guardar(t) != null) {
                    JOptionPane.showMessageDialog(rootPane, "Suprimento Efectuada!", "Informação", JOptionPane.INFORMATION_MESSAGE, Icone.INFORMACAO);
                    CaixaPane.actualizarTabela();
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Ocorreu um erro ao efectuar o Suprimento", "Erro", JOptionPane.ERROR_MESSAGE, Icone.ERRO);
                }

            } else {
                JOptionPane.showMessageDialog(rootPane, "Informe o valor", "Informação", 1, Icone.INFORMACAO);
            }
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(rootPane, "Informe um valor válido\n" + ex, "Informação", JOptionPane.INFORMATION_MESSAGE, Icone.INFORMACAO);
        }
    }

    public void setIsSuprimento(boolean isSuprimento) {
        this.isSuprimento = isSuprimento;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtObs;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
